export const projects: ProjectType[] = [
  {
    name: '',
    url: '',
    img: '',
    startDate: new Date('01/12/2020'),
    endDate: new Date('01/10/2020'),
    tags: [
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
    ],
  },
  {
    name: '',
    url: '',
    img: '',
    startDate: new Date('01/12/2020'),
    endDate: new Date('01/10/2020'),
    tags: [
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
    ],
  },
  {
    name: '',
    url: '',
    img: '',
    startDate: new Date('01/12/2020'),
    endDate: new Date('01/10/2020'),
    tags: [
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
    ],
  },
  {
    name: '',
    url: '',
    img: '',
    startDate: new Date('01/12/2020'),
    endDate: new Date('01/10/2020'),
    tags: [
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
    ],
  },
  {
    name: '',
    url: '',
    img: '',
    startDate: new Date('01/12/2020'),
    endDate: new Date('01/10/2020'),
    tags: [
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
    ],
  },
  {
    name: '',
    url: '',
    img: '',
    startDate: new Date('01/12/2020'),
    endDate: new Date('01/10/2020'),
    tags: [
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
    ],
  },
  {
    name: '',
    url: '',
    img: '',
    startDate: new Date('01/12/2020'),
    endDate: new Date('01/10/2020'),
    tags: [
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
    ],
  },
  {
    name: '',
    url: '',
    img: '',
    startDate: new Date('01/12/2020'),
    endDate: new Date('01/10/2020'),
    tags: [
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
    ],
  },
  {
    name: '',
    url: '',
    img: '',
    startDate: new Date('01/12/2020'),
    endDate: new Date('01/10/2020'),
    tags: [
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
    ],
  },
  {
    name: '',
    url: '',
    img: '',
    startDate: new Date('01/12/2020'),
    endDate: new Date('01/10/2020'),
    tags: [
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
    ],
  },
  {
    name: '',
    url: '',
    img: '',
    startDate: new Date('01/12/2020'),
    endDate: new Date('01/10/2020'),
    tags: [
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
    ],
  },
  {
    name: '',
    url: '',
    img: '',
    startDate: new Date('01/12/2020'),
    endDate: new Date('01/10/2020'),
    tags: [
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
    ],
  },
  {
    name: '',
    url: '',
    img: '',
    startDate: new Date('01/12/2020'),
    endDate: new Date('01/10/2020'),
    tags: [
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
    ],
  },
  {
    name: '',
    url: '',
    img: '',
    startDate: new Date('01/12/2020'),
    endDate: new Date('01/10/2020'),
    tags: [
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
    ],
  }
]